Repository pretenderjs/pretender, pull requests merged in 2020-02, with the labels that each got.

#288 Adds url parse and removes the usage of anchor
  iife-wrapper.js
  package.json
  rollup.config.js
  src/parse-url.ts
  yarn.lock
Labels: enhancement

#290 Removes unnecessary url-parse required from iife-wrapper
  iife-wrapper.js
Labels: bug

#294 Upgrade devDependencies and CI
  .travis.yml
  bower.json
  karma.conf.js
  package.json
  rollup.config.js
  test/passthrough_test.js
  yarn.lock
Labels: dependencies
